--- ### 项目配置
project:
  # 名称
  name: Beast
  # 应用名称
  app-name: Beast-Starter
  # 版本
  version: @project.version@
  # 描述
  description: 持续迭代优化的前后端分离中后台管理系统框架，开箱即用，持续提供舒适的开发体验。
  # 基本包
  base-package: cn.daben.beast
  ## 作者信息配置
  contact:
    name: Justubborn
    email: wubenhui@gmail.com
--- ### 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    enabled: ${springdoc.swagger-ui.enabled}
    path: /v3/api-docs
## 接口文档增强配置
knife4j:
  enable: ${springdoc.swagger-ui.enabled}
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
--- ### SA-TOKEN 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: BEAR-TOKEN
  # token有效期，单位s 默认30天, -1代表永不过期 
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) 
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token) 
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志 
  is-log: false
--- ### Spring 配置
spring:
  ## MVC 配置
  mvc:
    format:
      # 日期格式化（针对 java.util.Date）
      date-time: yyyy-MM-dd HH:mm:ss
  ## Jackson 配置
  jackson:
    # 时区配置
    time-zone: GMT+8
    # 日期格式化（针对 java.util.Date）
    date-format: yyyy-MM-dd HH:mm:ss
    # 序列化配置（Bean -> JSON）
    serialization:
      # 不允许序列化日期时以 timestamps 输出（默认：true）
      write-dates-as-timestamps: false
      # 允许序列化无属性的 Bean
      fail-on-empty-beans: false
    # 反序列化配置（JSON -> Bean）
    deserialization:
      # 允许反序列化不存在的属性
      fail-on-unknown-properties: false
