--- ### 项目配置
project:
  # 名称
  name: Beast
  # 应用名称
  app-name: Beast-Starter
  # 版本
  version: @project.version@
  # 描述
  description: 持续迭代优化的前后端分离中后台管理系统框架，开箱即用，持续提供舒适的开发体验。
  # 基本包
  base-package: cn.daben.beast
  ## 作者信息配置
  contact:
    name: Justubborn
    email: wubenhui@gmail.com
--- ### 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
    enabled: true
  api-docs:
    enabled: ${springdoc.swagger-ui.enabled}
    path: /v3/api-docs
  default-flat-param-object: true
## 接口文档增强配置
knife4j:
  enable: ${springdoc.swagger-ui.enabled}
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
--- ### SA-TOKEN 配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: BEAR-TOKEN
  # token有效期，单位s 默认30天, -1代表永不过期 
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) 
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token) 
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志 
  is-log: false
--- ### Spring 配置
spring:
  ## MVC 配置
  mvc:
    format:
      # 日期格式化（针对 java.util.Date）
      date-time: yyyy-MM-dd HH:mm:ss
  ## Jackson 配置
  jackson:
    # 时区配置
    time-zone: GMT+8
    # 日期格式化（针对 java.util.Date）
    date-format: yyyy-MM-dd HH:mm:ss
    # 序列化配置（Bean -> JSON）
    serialization:
      # 不允许序列化日期时以 timestamps 输出（默认：true）
      write-dates-as-timestamps: false
      # 允许序列化无属性的 Bean
      fail-on-empty-beans: false
    # 反序列化配置（JSON -> Bean）
    deserialization:
      # 允许反序列化不存在的属性
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
mybatis-plus:
  # 启动时是否检查 MyBatis XML 文件的存在（默认：false 不检查）
  check-config-location: true
  ## MyBatis 原生支持配置
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名）到经典 Java 属性名 aColumn（驼峰命名）的类似映射
    # 此属性在 MyBatis 中原默认值为 false，在 MyBatis-Plus 中，此属性也将用于生成最终的 SQL 的 select body，如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    map-underscore-to-camel-case: false
    # MyBatis 自动映射时未知列或未知属性处理策略，通过该配置可指定 MyBatis 在自动映射过程中遇到未知列或者未知属性时如何处理
    # NONE：不做任何处理 (默认值)；WARNING：以日志的形式打印相关警告信息；FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: WARNING
    # 日志配置
    # 默认：org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 更详细（会有性能损耗）：org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭（可单纯使用 p6spy 分析）：org.apache.ibatis.logging.nologging.NoLoggingImpl
beast:
  security:
    ## 字段加/解密配置
    crypto:
      enabled: true
      # 对称加密算法密钥
      password: abcdefghijklmnop
      # 非对称加密算法密钥（在线生成 RSA 密钥对：http://web.chacuo.net/netrsakeypair）
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAM51dgYtMyF+tTQt80sfFOpSV27a7t9uaUVeFrdGiVxscuizE7H8SMntYqfn9lp8a5GH5P1/GGehVjUD2gF/4kcCAwEAAQ==
      private-key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAznV2Bi0zIX61NC3zSx8U6lJXbtru325pRV4Wt0aJXGxy6LMTsfxIye1ip+f2WnxrkYfk/X8YZ6FWNQPaAX/iRwIDAQABAkEAk/VcAusrpIqA5Ac2P5Tj0VX3cOuXmyouaVcXonr7f+6y2YTjLQuAnkcfKKocQI/juIRQBFQIqqW/m1nmz1wGeQIhAO8XaA/KxzOIgU0l/4lm0A2Wne6RokJ9HLs1YpOzIUmVAiEA3Q9DQrpAlIuiT1yWAGSxA9RxcjUM/1kdVLTkv0avXWsCIE0X8woEjK7lOSwzMG6RpEx9YHdopjViOj1zPVH61KTxAiBmv/dlhqkJ4rV46fIXELZur0pj6WC3N7a4brR8a+CLLQIhAMQyerWl2cPNVtE/8tkziHKbwW3ZUiBXU24wFxedT9iV
    ## 密码编码器配置
    password:
      enabled: true
      # BCryptPasswordEncoder
      encoding-id: bcrypt
  ## 行为验证码
  captcha:
    behavior:
      enabled: true
      cache-type: REDIS
      water-mark:
      # 一分钟内接口请求次数限制开关（默认：0，关闭，开启后下方失败锁定配置才会生效）
      req-frequency-limit-enable: 0
      # 一分钟内验证码最多失败次数限制（默认：5次）
      req-get-lock-limit: 5
      # 一分钟内验证码最多失败次数限制达标后锁定时间（默认：300秒）
      req-get-lock-seconds: 300
    ## 图形验证码
    graphic:
      # 类型
      type: SPEC
      # 内容长度
      length: 4
      # 过期时间
      expirationInMinutes: 2
